### ISSUE TITLE
[bug] Advanced portal gun, used in FTB chunk claims, crashes the server

### ISSUE THREAD

**Issue by Slugstur** [Direwolf20-MC/JustDireThings#110]
Not sure which side of the two mods this bug is on, but reporting it here anyways.

When you have JDT in a pack together with FTB claimed chunks, and you use the advanced portal gun to teleport to someone else's claim, the server crashes. Just had this happen in ATM10. Reproduced it several times, always crashes.

**Comment by Direwolf20-MC** [comment]
Can you post the crash log? :)

**Comment by Slugstur** [comment]
Got this from server owner
`Stacktrace:
    at TRANSFORMER/justdirethings@0.11.12/com.direwolf20.justdirethings.common.entities.PortalEntity.tickCooldowns(PortalEntity.java:106) ~[justdirethings-0.11.12.jar%23347!/:?] {re:classloading}
    at TRANSFORMER/justdirethings@0.11.12/com.direwolf20.justdirethings.common.entities.PortalEntity.tick(PortalEntity.java:76) ~[justdirethings-0.11.12.jar%23347!/:?] {re:classloading}
    at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:772) ~[server-1.21-20240613.152323-srg.jar%23264!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:kubejs.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:A}
    at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[server-1.21-20240613.152323-srg.jar%23264!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:xycraft_core.mixins.json:LevelRainShieldMixin from mod xycraft_core,pl:mixin:APP:kubejs.mixins.json:LevelMixin from mod kubejs,pl:mixin:A}
    at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:418) ~[server-1.21-20240613.152323-srg.jar%23264!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus from mod comforts,pl:mixin:APP:kubejs.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:A}
    at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[server-1.21-20240613.152323-srg.jar%23264!/:?] {re:classloading}
-- Entity being ticked --
Details:
    Entity Type: justdirethings:portal_entity (com.direwolf20.justdirethings.common.entities.PortalEntity)
    Entity ID: 90463
    Entity Name: entity.justdirethings.portal_entity
    Entity's Exact location: -4315.50, 139.00, -20608.00
    Entity's Block location: World: (-4316,139,-20608), Section: (at 4,11,0 in -270,8,-1288; chunk contains blocks -4320,-64,-20608 to -4305,319,-20593), Region: (-9,-41; contains chunks -288,-1312 to -257,-1281, blocks -4608,-64,-20992 to -4097,319,-20481)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: null
Stacktrace:`

**Comment by Calmingstorm** [comment]
[crashlogs.zip](https://github.com/user-attachments/files/16288017/crashlogs.zip)

**Comment by Slugstur** [comment]
[crashlogs.zip](https://github.com/user-attachments/files/16288016/crashlogs.zip)
Got the full logs now of several crashes. Hope it helps!

**Comment by Direwolf20-MC** [comment]
I'm not sure why the chunk claiming was causing that, and I couldn't reproduce it with just my mod and FTB's in my dev environment - but I added a nullcheck that should prevent this kind of thing in the future! :)

Let me know if it keeps happening after 0.11.13
