### ISSUE TITLE
Shooting a projectile from infinity launcher through a portal across dimensions crashes game

### ISSUE THREAD

**Issue by TJM** [Direwolf20-MC/JustDireThings#294]
### Just Dire Things version

1.4.8

### Minecraft Version

1.21.1

### (Neo)Forge Version

21.1.74

### Modpack & Version

Direwolf20 1.21 1.4.1

### Do you have optifine or Rubidium installed?

None

### Describe the issue

Shooting a projectile from infinity launcher through a portal across dimensions crashes game

### Steps to reproduce

1. Use portal gun to create a portal between overworld and nether (probably works for other cross-dimensions)
2. Use the "Infinity Launcher" from industrial foregoing to shoot a projectile (toilet plunger) through the portal
3. crash :(

### Expected behaviour

The projectile should either hit the portal and stop or go through without crashing the game

### Screenshots

N/A

### Log files

```
[23Nov2024 01:21:04.693] [Render thread/INFO] [net.minecraft.advancements.AdvancementTree/]: Loaded 189 advancements
[23Nov2024 01:21:28.459] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Saving entity NBT
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1041) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Cannot encode empty ItemStack
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.save(ItemStack.java:409) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.projectile.AbstractArrow.addAdditionalSaveData(AbstractArrow.java:529) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:1723) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.restoreFrom(Entity.java:2567) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.projectile.Projectile.restoreFrom(Projectile.java:99) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.teleportTo(Entity.java:2757) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/justdirethings@1.4.8/com.direwolf20.justdirethings.common.entities.PortalEntity.teleport(PortalEntity.java:409) ~[justdirethings-1.4.8.jar%23572!/:?]
	at TRANSFORMER/justdirethings@1.4.8/com.direwolf20.justdirethings.common.entities.PortalEntity.teleportCollidingEntities(PortalEntity.java:161) ~[justdirethings-1.4.8.jar%23572!/:?]
	at TRANSFORMER/justdirethings@1.4.8/com.direwolf20.justdirethings.common.entities.PortalEntity.tick(PortalEntity.java:92) ~[justdirethings-1.4.8.jar%23572!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23443!/:?]
	... 5 more
[23Nov2024 01:21:28.469] [Server thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 70483711-89ac-47ef-adff-dc657b6aa223
[23Nov2024 01:21:29.488] [Server thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID fa44f007-f02e-414d-95db-6b16623bbb3a
[23Nov2024 01:21:29.489] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /Users/tommy/Library/Application Support/.ftba/instances/ftb presents direwolf20 121/crash-reports/crash-2024-11-23_01.21.28-server.txt
[23Nov2024 01:21:29.489] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[23Nov2024 01:21:29.490] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[23Nov2024 01:21:29.494] [Render thread/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID fde83efb-8a36-4d33-bb12-bcc51757bb31
[23Nov2024 01:21:29.494] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
```

### Additional information

Vanilla arrows seem to work

**Comment by James103** [comment]
> Use the "Infinity Launcher" from industrial foregoing to shoot a projectile (toilet plunger)

Do you crash or get a similar error if you
a) Save and quit the world (disconnect) before the projectile lands or goes through the portal?
b) Go away from spawn chunks, launch the projectile, then run `/tp @s ~1000 ~ ~` before it lands?

**Comment by TJM** [comment]
I am not sure how I can do that, it is like an arrow, it shoots very fast :)

**Comment by TJM** [comment]
I probably should have said it crashed the server. I had to login to creeperhost to restart.

**Comment by Direwolf20-MC** [comment]
After some testing, I believe this issue is on Foregoing's side. I'll close this one, and I opened a bug report over there.
